{'messageVersion': '1.0', 
 'invocationSource': 'DialogCodeHook', 
 'userId': 'fdu9m0c6kla4qhbxsxyngpzp5wofd1nx', 
 'sessionAttributes': {}, 
 'requestAttributes': None, 
 'bot': {'name': 'AcademicBot_dev', 
         'alias': '$LATEST', 
         'version': '$LATEST'
         }, 
 'outputDialogMode': 'Text', 
 'currentIntent': {'name': 'Prerequisites', 
                   'slots': {'slotOne': 'Engineering Graphics'}, 
                   'slotDetails': {'slotOne': {'resolutions': [{'value': 'Engineering Graphics'}], 'originalValue': 'Engineering Graphics'}}, 
                   'confirmationStatus': 'None', 'nluIntentConfidenceScore': 1.0},
'alternativeIntents': [{'name': 'AMAZON.FallbackIntent', 'slots': {}, 'slotDetails': {}, 'confirmationStatus': 'None', 'nluIntentConfidenceScore': None}, 
                       {'name': 'Welcome_dev', 'slots': {}, 'slotDetails': {}, 'confirmationStatus': 'None', 'nluIntentConfidenceScore': 0.43}
                       ], 
'inputTranscript': 'Can I take Engineering Graphics?', 
'recentIntentSummaryView': None, 
'sentimentResponse': None, 
'kendraResponse': None}



prerequisites = {
        'Digital Logic Design': 'ECE1001 - Fundamentals of Electrical Engineering or ECE1002 - Fundamentals of Electrical and Electronics Engineering',
        'Object Oriented Programming': 'CSE1004 - Problem Solving using JAVA',
        'Design and Analysis of Algorithms': 'CSE2001 - Data structures and algorithms',
        'Database Management Systems': 'CSE2001 - Data structures and algorithms',
        'Computer Networks': 'CSE2005 - Object Oriented Programming',
        'Optimization Techniques': 'MAT1001 - Calculus for Engineering',
        'Data Warehousing and Data Mining': 'CSE2007 - Database Management Systems',
        'Mobile Application Development': 'CSE2007-Database Management Systems',
        'Artificial Intelligence': 'CSE1004-Problem Solving using Java',
        'Network Programming': 'CSE3003 - Computer Networks',
        'Network Security': 'CSE1007 - Introduction to Cryptography',
        'Distributed Systems': 'CSE2008 - Operating System',
        'Parallel Computing': 'CSE2001 - Data structures and algorithms',
        'Agile Development Process': 'CSE1005 - Software Engineering',
        'Information Retrieval': 'CSE2001 - Data structures and algorithms',
        'Data Visualization': 'CSE1006 - Foundation of Data Analytics',
        'Cyber Security and Digital Forensics': 'CSE1007 - Introduction to Cryptography',
        'Wireless and Mobile Security': 'CSE3012 - Network Security',
        'Wireless and Mobile Computing': 'CSE3003 - Computer Networks',
        'Network Design and Performance Evaluation': 'CSE3003 - Computer Networks',
        'Web Application Security': 'CSE3012 - Network Security',
        'Deep Learning': 'CSE3008 - Introduction to Machine Learning',
        'Database Administration': 'CSE2007 - Database Management Systems',
        'Secure Group Communications': 'CSE1007 - Introduction to Cryptography',
        'Software Configuration Management': 'CSE1005 - Software Engineering',
        'Software Quality and Reliability': 'CSE1005 - Software Engineering',
        'Product Definition and Validation': 'CSE1005 - Software Engineering',
        'Reverse Engineering': 'CSE1005 - Software Engineering',
        'Team Software Process': 'CSE1005 - Software Engineering',
        'Network Administration': 'CSE3003 - Computer Networks',
        'Health Care Analytics': 'CSE1006 - Foundation of Data Analytics',
        'Microcontrollers and Interfacing': 'ECE1003 - Digital logic Design',
        'Cloud Computing': 'CSE3003 - Computer Networks',
        'No SQL Databases': 'CSE2007 - Database Management Systems',
        'Introduction to Machine Learning': 'MAT2003 - Optimization Techniques',
        'Secure Coding': 'CSE2001 - Data structures and algorithms',
        'Computer Vision and Robotics': 'CSE4007 - Digital Image Processing',
        'Applications of Artificial Intelligence': 'CSE3002 - Artificial Intelligence',
        'Agent Based Intelligent Systems' : 'CSE3002 - Artificial Intelligence',
        'Introduction to Cognitive Modelling' : 'CSE3002 - Artificial Intelligence',
        'Introduction to Blockchain Technology' : 'CSE1007 - Introduction to Cryptography',
        'Applications of Differential and Difference Equations' : 'MAT1001 - Calculus for Engineers',
        'Condensed Matter Physics' : 'PHY1007 - Principles of Electronics or PHY1006 - Physics of Materials',
        'Numerical Methods for Engineers' : 'MAT1002 - Applications of Differential and Difference Equations',
        'Complex Variables and Partial Differential Equations' : 'MAT1002 - Applications of Differential and Difference Equations',
        'Fundamentals of Supply Chain Analytics' : 'CSE1006 - Foundations for Data Analytics',
        'Proficiency in French' : 'FRL1001 - Basic French',
        'Data Structures and Algorithms' : 'CSE1004 - Problem Solving using JAVA',
    }


# The Pre-requisite for {course} course are 